MULE-18307: Using "payload" in an expression for refreshTokenWhen property results in an Error
mulesoft/mule-http-connector pull request #469
Opened 2020-09-04 13:47 UTC by pabloperalta

2020-09-04 17:56 UTC, elrodro83 approved these changes

2020-09-04 17:56 UTC, elrodro83 commented on src/main/java/org/mule/extension/http/api/request/authentication/HttpRequestAuthentication.java
> +  default boolean isConsumesPayload() {
better called `readsPayload`

2020-09-04 17:56 UTC, elrodro83 commented on src/main/java/org/mule/extension/http/api/request/authentication/HttpRequestAuthentication.java
> +  default boolean isConsumesPayload() {
add javadoc, including `@since` version

2020-09-04 17:57 UTC, elrodro83 commented on src/main/java/org/mule/extension/http/api/request/authentication/HttpRequestAuthentication.java
> +  default boolean isConsumesPayload() {
also, what does `payload` mean in this context?

2020-09-04 18:00 UTC, elrodro83 requested changes

2020-09-04 18:00 UTC, elrodro83 commented on src/main/java/org/mule/extension/http/api/request/authentication/HttpRequestAuthentication.java
> +  default boolean isConsumesPayload() {
so: `readsAuthenticatedResponseBody`?

2020-09-04 18:38 UTC, pabloperalta commented
--validate

2020-09-04 19:06 UTC, pabloperalta commented on src/main/java/org/mule/extension/http/api/request/authentication/HttpRequestAuthentication.java
> +  default boolean isConsumesPayload() {
Added @since 1.5.20

2020-09-04 19:15 UTC, elrodro83 requested changes

2020-09-04 19:15 UTC, elrodro83 commented on src/main/java/org/mule/extension/http/api/request/authentication/HttpRequestAuthentication.java
> +   * Indicates if the response body is read in the process of handling it
`is read` -> `may be read`

2020-09-04 19:15 UTC, elrodro83 commented on src/main/java/org/mule/extension/http/api/request/authentication/HttpRequestAuthentication.java
> +   * @return Whether the response body will be read or not
`will` -> `may`

2020-09-07 12:47 UTC, elrodro83 approved these changes

2020-09-07 14:29 UTC, merged